# Generated by Django 2.2.2 on 2019-06-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190613_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='top_three_sales',
        ),
        migrations.AddField(
            model_name='product',
            name='image_src',
            field=models.CharField(default='', max_length=500),
        ),
    ]
