# Generated by Django 2.2.2 on 2019-06-19 19:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_firstpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstpage',
            name='first_part',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='firstpage',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
