# Generated by Django 2.2.2 on 2019-06-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190619_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='product',
            name='autonomy',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='cons',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='pros',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='short_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='speed_max',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='user_weight_max',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
