# Generated by Django 2.2.2 on 2019-06-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190621_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(default='', max_length=500),
        ),
    ]
