# Generated by Django 2.2.2 on 2019-06-21 15:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190621_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cons',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='pros',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
