# Generated by Django 2.2.2 on 2019-06-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitedpage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='visitedpage',
            name='source_site',
        ),
        migrations.RemoveField(
            model_name='post',
            name='visited_page',
        ),
        migrations.DeleteModel(
            name='SourceSite',
        ),
        migrations.DeleteModel(
            name='VisitedPage',
        ),
    ]
